# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fb14feb798382b874203cb8751e20f21efc483cba3c41ef996f5b484cf7f859ef4b6fa4af1b6e04a42cf8bbfaaa0d24769b2b074951b5193b33d5c3b5af7c3f2

test:
  secret_key_base: 8f684007f307b16b6a1e1bbe741399158b77bb54bcc35728992c4d202e15c91d340a9c129b04e3d5bbf9933f2f8a9d061136a0a4e6d46d3db9fd06a216f6f2e0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
